apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
  labels:
    app: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image: itzg/minecraft-server:latest
        ports:
        - containerPort: 25565
          name: minecraft
          protocol: TCP
        env:
        - name: EULA
          value: "TRUE"
        - name: MEMORY
          value: "4G"
        - name: DIFFICULTY
          value: "normal"
        resources:
          requests:
            memory: "4Gi"
            cpu: "1000m"
          limits:
            memory: "8Gi"
            cpu: "1000m"
