apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data
spec:
  storageClassName: local-path  # Add this line
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
