apiVersion: v2
name: edge-ai-mc-server
description: Custom MC server chart
type: application

# This is the version of your chart
version: 0.1.0

# This is the version of the application
appVersion: "1.21.11"

dependencies:
  - name: minecraft
    version: 5.0.0
    repository: https://itzg.github.io/minecraft-server-charts/
